// webapp/src/categoryList.tsx
import { createElement } from "./tools/jsxFactory";

export class CategoryList {
  props: {
    categories: string[];
    selectedCategory: string;
    callback: (selected: string) => void;
  };

  getContent(): HTMLElement {
    return (
      <div>
        {["All", ...this.props.categories].map((c) =>
          this.getCategoryButton(c)
        )}
      </div>
    );
  }

  getCategoryButton(cat?: string): HTMLElement {
    const selected =
      this.props.selectedCategory === undefined
        ? "All"
        : this.props.selectedCategory;
    const btnClass = selected === cat ? "btn-primary" : "btn-secondary";
    return (
      <button
        className={`btn btn-block ${btnClass}`}
        onclick={() => this.props.callback(cat)}
      ></button>
    );
  }
}

// vueapp/src/components/CategoryList.vue
<template>
  <div>
    <button
      v-for="c in categories"
      v-bind:key="c"
      v-bind:class="getButtonClasses(c)"
      @click="selectCategory(c)"
    >
      {{ c }}
    </button>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";

export default defineComponent({
  name: "CategoryList",
  props: {
    categories: {
      type: Object as PropType<string[]>,
      required: true,
    },
    selected: {
      type: String as PropType<string>,
    },
  },
  methods: {
    selectCategory(category: string) {
      this.$emit("selectCategory", category);
    },
    getButtonClasses(category: string): string {
      const btnClass =
        this.selected === category ? "btn-primary" : "btn-secondary";
      return `btn btn-block ${btnClass}`;
    },
  },
});
</script>
