// angularapp/src/app/categoryList.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";

@Component({
    selector: "category-list",
    templateUrl: "./categoryList.component.html"
})
export class CategoryList {
    @Input()
    selected!: string

    @Input()
    categories!: string[]

    @Output()
    selectCategory = new EventEmitter<string>();

    getBtnClass(category: string): string {
        return "btn btn-block " +
            (category === this.selected ? "btn-primary" : "btn-secondary");
    }
}

// vueapp/src/components/CategoryList.vue
<template>
  <div>
    <button
      v-for="c in categories"
      v-bind:key="c"
      v-bind:class="getButtonClasses(c)"
      @click="selectCategory(c)"
    >
      {{ c }}
    </button>
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";

export default defineComponent({
  name: "CategoryList",
  props: {
    categories: {
      type: Object as PropType<string[]>,
      required: true,
    },
    selected: {
      type: String as PropType<string>,
    },
  },
  methods: {
    selectCategory(category: string) {
      this.$emit("selectCategory", category);
    },
    getButtonClasses(category: string): string {
      const btnClass =
        this.selected === category ? "btn-primary" : "btn-secondary";
      return `btn btn-block ${btnClass}`;
    },
  },
});
</script>
