// angularapp/src/app/header.component.ts
import { Component, EventEmitter, Input, Output } from "@angular/core";
import { Order } from "./data/entities";

@Component({
    selector: "header",
    templateUrl: "./header.component.html"
})
export class Header {
    @Input()
    order!: Order;

    @Output()
    submit = new EventEmitter<void>();

    get headerText(): string {
        const count = this.order.productCount;
        return count === 0 ? "(No Selection)" : `${count} product(s), $${this.order.total.toFixed(2)}`
    }
}

// reactapp/src/header.tsx
import React, { Component } from "react";
import { Order } from "./data/entities";

interface Props {
  order: Order;
}

export class Header extends Component<Props> {
  render() {
    const count = this.props.order.productCount;
    return (
      <div className="p-1 bg-secondary text-white text-right">
        {count === 0
          ? "(No Selection)"
          : `${count} product(s), $${this.props.order.total.toFixed(2)}`}
        <button className="btn btn-sm btn-primary m-1">Submit Order</button>
      </div>
    );
  }
}
